@extends('layouts.soundia')
@section('content')
@php
$page = [
 'ru'=>['title'=>'О студии','lead'=>'Добро пожаловать в нашу студию!','intro'=>'Мы — команда увлеченных профессионалов, специализирующихся на создании уникального аудиосодержания. Наша студия предлагает полный спектр услуг по разработке аудиогидов, квестов, игр и 3D аудио, превращая ваши идеи в захватывающие аудиопроекты. Мы создаем аудио с 2014 года.','servicesLabel'=>'Наши услуги'],
 'lv'=>['title'=>'Studija','lead'=>'Laipni lūdzam mūsu studijā!','intro'=>'Mēs esam aizrautīgu profesionāļu komanda, kas specializējas unikāla audio satura radīšanā. Studija piedāvā pilnu pakalpojumu klāstu audiogidu, kvestu, spēļu un 3D audio izstrādei, pārvēršot idejas aizraujošos audio projektos. Mēs veidojam audio kopš 2014. gada.','servicesLabel'=>'Mūsu pakalpojumi'],
 'en'=>['title'=>'About studio','lead'=>'Welcome to our studio!','intro'=>'We are a team of passionate professionals specializing in unique audio content. Our studio offers a full range of services for audio guides, quests, games and 3D audio, turning ideas into engaging audio projects. We have been creating audio since 2014.','servicesLabel'=>'Our services']
][$locale];
@endphp
<main class="about-company-page"><section class="about-company-hero" aria-labelledby="about-company-title"><figure class="about-company-hero__image"><img src="https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?auto=format&fit=crop&w=1800&q=85" alt="{{ $page['title'] }}"><div class="about-company-map" aria-hidden="true"><span></span><span></span><span></span><span></span></div></figure><div class="about-company-hero__copy"><h1 id="about-company-title">{{ $page['title'] }}</h1><p>{{ $page['lead'] }}</p><p class="about-company-intro">{{ $page['intro'] }}</p><div class="about-company-process" aria-label="{{ $page['servicesLabel'] }}"><span>{{ $page['servicesLabel'] }}</span><ul>@foreach($content['services'] as $service)<li><strong>{{ $service['title'][$locale] }}</strong><em>{{ $service['description'][$locale] }}</em></li>@endforeach</ul></div><div class="about-company-support"><img class="about-company-support__photo" src="{{ asset('Project.png') }}" alt=""><div class="about-company-support__text"><p>SIA ZENITH 2024.gada 5.aprīlī noslēdza līgumu Nr.17.2-5-L-2024/183 ar Latvijas Investīciju un attīstības aģentūru par atbalsta saņemšanu uzņēmuma digitalizācijas programmā.</p><p>Uzņēmums “ZENITH” ir ieguvis sociālā uzņēmuma statusu un saņēmis ALTUM ES grantu.</p></div></div></div></section></main>
@endsection
