@extends('layouts.soundia')
@section('content')
@php
$copy = [
 'ru'=>['eyebrow'=>'Обучение','title'=>'Учимся работать со звуком.','intro'=>'Практические курсы Soundia: запись, голос, саунд-дизайн и музыкальный продакшн.','request'=>'Оставить заявку','programs'=>'Программы','headline'=>'Коротко. Практично. До готового проекта.','stats'=>'3 курса · свидетельство · очный формат','details'=>'Подробнее о курсе +','enroll'=>'Записаться'],
 'lv'=>['eyebrow'=>'Apmācības','title'=>'Mācāmies strādāt ar skaņu.','intro'=>'Soundia praktiskie kursi: ieraksts, balss, skaņas dizains un mūzikas producēšana.','request'=>'Atstāt pieteikumu','programs'=>'Programmas','headline'=>'Īsi. Praktiski. Līdz gatavam projektam.','stats'=>'3 kursi · apliecība · klātienē','details'=>'Vairāk par kursu +','enroll'=>'Pieteikties'],
 'en'=>['eyebrow'=>'Training','title'=>'Learn to work with sound.','intro'=>'Practical Soundia courses: recording, voice, sound design and music production.','request'=>'Send a request','programs'=>'Programs','headline'=>'Concise. Practical. Up to a finished project.','stats'=>'3 courses · certificate · in person','details'=>'More about the course +','enroll'=>'Enroll']
][$locale];
$courses = [
 ['slug'=>'sound-design','title'=>['ru'=>'Основы звукового дизайна и аудиопостобработки','lv'=>'Skaņas dizaina pamati un audio pēcapstrāde','en'=>'Sound Design and Audio Post-Production Basics'],'meta'=>['ru'=>'72 часа · очно','lv'=>'72 stundas · klātienē','en'=>'72 hours · in person'],'level'=>['ru'=>'Начальный уровень','lv'=>'Iesācēju līmenis','en'=>'Beginner level'],'text'=>['ru'=>'Запись, монтаж, обработка, шумоподавление, полевые записи и сведение.','lv'=>'Ieraksts, montāža, apstrāde, trokšņu tīrīšana, lauka ieraksti un miksēšana.','en'=>'Recording, editing, processing, noise cleanup, field recording and mixing.'],'tags'=>['ru'=>['DAW','EQ','Компрессия','Мастеринг'],'lv'=>['DAW','EQ','Kompresija','Māsterings'],'en'=>['DAW','EQ','Compression','Mastering']]],
 ['slug'=>'voice-recording','title'=>['ru'=>'Основы записи голоса и аудиопостобработки','lv'=>'Balss ieraksta un audiopēcapstrādes pamati','en'=>'Voice Recording and Audio Post-Production Basics'],'meta'=>['ru'=>'24 часа · очно','lv'=>'24 stundas · klātienē','en'=>'24 hours · in person'],'level'=>['ru'=>'Без опыта','lv'=>'Bez priekšzināšanām','en'=>'No experience required'],'text'=>['ru'=>'Чистая запись речи для подкастов, интервью, voice-over и видео.','lv'=>'Tīrs balss ieraksts podkāstiem, intervijām, voice-over un video saturam.','en'=>'Clean voice recording for podcasts, interviews, voice-over and video.'],'tags'=>['ru'=>['Голос','Монтаж','Шум','Публикация'],'lv'=>['Balss','Montāža','Troksnis','Publicēšana'],'en'=>['Voice','Editing','Noise','Publishing']]],
 ['slug'=>'music-production','title'=>['ru'=>'Аудиопродакшн и постобработка музыки','lv'=>'Audio producēšana un mūzikas pēcapstrāde (padziļināts kurss)','en'=>'Audio Production and Music Post-Production'],'meta'=>['ru'=>'72 часа · очно','lv'=>'72 stundas · klātienē','en'=>'72 hours · in person'],'level'=>['ru'=>'Углублённый уровень','lv'=>'Padziļināts līmenis','en'=>'Advanced level'],'text'=>['ru'=>'Музыка от идеи до финального мастера: MIDI, инструменты, микс и мастеринг.','lv'=>'Mūzika no idejas līdz gala māsteram: MIDI, instrumenti, mikss un māsterings.','en'=>'Music from idea to final master: MIDI, instruments, mix and mastering.'],'tags'=>['ru'=>['MIDI','Сведение','Production','Master'],'lv'=>['MIDI','Miksēšana','Production','Master'],'en'=>['MIDI','Mixing','Production','Master']]]
];
@endphp
<main class="courses-page courses-page--cinematic"><section class="courses-hero"><div class="container courses-hero__inner"><div class="courses-hero__copy"><p class="courses-hero__eyebrow">{{ $copy['eyebrow'] }}</p><h1>{{ $copy['title'] }}</h1><p>{{ $copy['intro'] }}</p><button class="courses-hero__button" type="button" data-modal-open="order-modal">{{ $copy['request'] }}</button></div><div class="courses-hero__wave" aria-hidden="true">@for($i=0;$i<34;$i++)<span style="--h:{{ 18 + (($i * 7) % 48) }}px;--o:{{ 0.28 + ($i % 5) * 0.12 }}"></span>@endfor</div></div></section><section class="courses-showcase"><div class="container"><div class="courses-showcase__top"><div><p>{{ $copy['programs'] }}</p><h2>{{ $copy['headline'] }}</h2></div></div><div class="courses-showcase__grid">@foreach($courses as $course)<article class="course-tile"><span class="course-tile__number">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><p>{{ $course['meta'][$locale] }}</p><h3>{{ $course['title'][$locale] }}</h3><span>{{ $course['level'][$locale] }}</span></div><p>{{ $course['text'][$locale] }}</p><ul>@foreach($course['tags'][$locale] as $tag)<li>{{ $tag }}</li>@endforeach</ul><a class="course-tile__details-link" href="{{ url('/courses/'.$course['slug']) }}">{{ $copy['details'] }}</a><button type="button" data-modal-open="order-modal">{{ $copy['enroll'] }}</button></article>@endforeach</div></div></section></main>
@endsection

